name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]  # ou "master" selon votre branche principale

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository_owner }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}/quantum:latest
            ghcr.io/${{ steps.string.outputs.lowercase }}/quantum:${{ github.sha }}
